# fly.toml app configuration file generated for dhariri-com on 2024-12-23T16:33:24+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dhariri-com'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
