[tool.poetry]
name = "site"
version = "0.1.0"
description = "David Hariri's place on the web"
authors = ["David Hariri <david.hariri@gmail.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.0"
gunicorn = "^22.0.0"
flask-caching = "^2.1.0"
rfeed = "^1.1.1"
sentry-sdk = "^2.2.0"
markdown = "^3.5"
pydantic = "^2.4.2"
python-frontmatter = "^1.0.0"
python-dotenv = "^1.0.0"
pygments = "^2.17.2"
click = "^8.1.7"
pymongo = "^4.10.1"
pydantic-settings = "^2.5.2"
python-slugify = "^8.0.4"
openai = "^1.51.2"
boto3 = "^1.35.42"
tweepy = "^4.14.0"
beautifulsoup4 = "^4.12.3"
pymdown-extensions = "^10.12"


[tool.poetry.group.dev.dependencies]
black = "^24.3.0"
mypy = "^1.6.1"
debugpy = "^1.8.0"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
